### ISSUE TITLE
Auto hold gets all players to stop with latest version and latest patch

### ISSUE THREAD

**Issue by danne77sthlm** [Mogli12/GearboxAddon#64]
Hi,
Disabled all mods to test this, have latest patch to the game as well

What happens is that all players on dedi server stops when someone is chatting and vehicle is placed in "auto hold" , all players gets put in same mode and cant get out from it

**Comment by Mogli12** [comment]
The problem should be fixed in the latest version.

**Comment by danne77sthlm** [comment]
Hi Mogli,

Sorry to have to inform you that this issue is still not resolved :(

**Comment by MaxterTM** [comment]
Same problem yesterday at the dedicated server. Latest server version and latest gearbox (1.9.3.8)
No way to play with gearbox...

**Comment by Mogli12** [comment]
Hallo,  die letzte Korrektur für MP war in 1.9.3.9. Es ist also klar,  dass es mit 1.9.3.8 noch nicht funktioniert.

**Comment by Mogli12** [comment]
Hi, ab Version 1.9.4.3 wird MP nicht mehr unterstützt. Viele Grüße
